### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by BamideleAriwodola** [spjeff/infopathdb#1]
Hi Jeff,

I have been unable to edit the code after download.
I keep getting version incompatibility messages with sharepoint version. I have tried opening it with Visual Studio 2012 & 2015.

- What is the preferred visual studio version to work with please?

- Also I get a warning message stating that SharePoint Foundation or Server 2010 must be installed. My installed SharePoint version is 2013.

- The Referenced component Newtonsoft.json could not be found

Please help with how I can resolve these.

**Comment by spjeff** [comment]
All good questions.

1)  Visual Studio 2013 on SharePoint 2010, was original way the project was created.   However never versions should work too.  

2)  Yes, may need to remove "Microsoft.SharePoint.dll" and add the newer version reference.

3)  Probably need to run Nuget "Update-Package" on the Visual Studio console.  https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages

**Comment by BamideleAriwodola** [comment]
Thanks for your swift response.

When I try opening the project with VS 2015, I get 'This project is incompatible with the current edition'.

Does this mean I can only open it on VS 2013?

**Comment by spjeff** [comment]
Try making a new SharePoint server side project (VS 2015 + SharePoint 2013 DLL).

Adding the InfoPathDB.asmx, /ISAPI/, and /Layouts/ components to populate will provide both the Web Service ASMX endpoint and front end GUI ASPX.  

The project shell is disposable.  The core (ASMX+ASPX) are what is really needed to run.

**Comment by BamideleAriwodola** [comment]
Hi Jeff,

Are you saying I need just these two files(**InfoPathDB.aspx.cs** and **InfoPath.asmx.cs**) from the project folders to run? 

Also do I deploy the project to a root site collection or central administration?
