### ISSUE TITLE
Access Denied/401 Unauthorized/ Internet Explorer Null Reference Exception

### ISSUE THREAD

**Issue by BamideleAriwodola** [spjeff/infopathdb#2]
Hi Jeff,
I was finally able to deploy the solution to my SharePoint 2013 farm.

Now I've hit another roadblock as I tried to use the web services as an xml datasource in SSRS and it keeps throwing a null exception during report dataset creation.

Also using the "Soap Invoke form" when I click the Query form library method and passing 4/5 of the parameters in internet explorer browser, it returns a null reference exception message. When I run using the same number of parameters on other browsers(chrome and mozilla) I can see the content of my form library.

Any ideas as to why this is happening? and does this have any correlation with using the web service as an SSRS datasource/dataset?

**Comment by spjeff** [comment]
Excellent progress.

Do you have a line number for the null exception?  The HTTP traffic must be
different somehow from those clients.  Potentially HTTP headers.

Does ULS or IIS log show more detail on the failed HTTP requests?

**Comment by BamideleAriwodola** [comment]
Here are some screenshots.

Screenshot 1 - Parameters set before clicking invoke
Screenshot 2 - After clicking invoke via "soap invoke form" 
Screenshot 3 - exception thrown when debugging the webservice 
Screenshot 4 - Error message I get when trying to create an ssrs dataset


![param](https://user-images.githubusercontent.com/23080445/35431336-561a147c-027c-11e8-88a6-4a919caa9a63.PNG)
![exception](https://user-images.githubusercontent.com/23080445/35431256-120d8282-027c-11e8-8826-bd83314a8d9f.PNG)
![accessdenied](https://user-images.githubusercontent.com/23080445/35431467-e139f46e-027c-11e8-8a4e-b18fb007208e.png)
![dataset](https://user-images.githubusercontent.com/23080445/35431746-fb851208-027d-11e8-8cda-ffb37231225d.PNG)

I hope these give you a clearer insight into possible solutions to these issues.

Thanks.

**Comment by BamideleAriwodola** [comment]
The current user variable in the was returning null for some reason, and this was the cause of system.nullreference exception.

Now I need to use this webservice as a dataset in ssrs. any help on how to use this in ssrs would be great.

**Comment by befikirhm** [comment]
@BamideleAriwodola  I installed InfoPathDB years back when the project was hosted on Codplex. I was getting random Access denied/ system.nullreference exception. After months of debugging, fiddling and googling the problem, I finally got it to work in my environment by modifying the web.config at C:\Program Files\Common Files\microsoft shared\Web Server Extensions\15\ISAPI\InfoPathDB
I added the below line after `</webservices>` tag.
`    <authorization>
         <deny users="?" />
    </authorization>`
InfoPathDB still deployed and working perfect for reporting on deep nested repeating tables forms.

**Comment by spjeff** [comment]
Thanks @befikirhm 

I updated that line in web.config just now.

https://github.com/spjeff/infopathdb/blob/master/InfoPathDB/ISAPI/InfoPathDB/web.config

**Comment by befikirhm** [comment]
Thanks Jeff @spjeff 
I just did quick test on new dev machine. And I confirmed this update on web.config is the right solution.
Jeff, your InfoPathDB project helped me a lot. Thank you.

**Comment by spjeff** [comment]
Excellent.  Glad you found the project helpful.

Saved me lots of time querying and reporting with InfoPath XML.
